// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_poly_residualize_matrix
NumericMatrix cpp_poly_residualize_matrix(NumericMatrix Z, NumericMatrix A, int degree, bool interactions, double ridge);
RcppExport SEXP _BLITZ_cpp_poly_residualize_matrix(SEXP ZSEXP, SEXP ASEXP, SEXP degreeSEXP, SEXP interactionsSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< bool >::type interactions(interactionsSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_poly_residualize_matrix(Z, A, degree, interactions, ridge));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cit_oob_score_min_node_matrix
NumericMatrix cpp_cit_oob_score_min_node_matrix(NumericMatrix X, NumericMatrix Y, IntegerVector min_node_candidates, double learning_rate, double subsample, int max_depth, int min_bucket, int mtry, int seed_base);
RcppExport SEXP _BLITZ_cpp_cit_oob_score_min_node_matrix(SEXP XSEXP, SEXP YSEXP, SEXP min_node_candidatesSEXP, SEXP learning_rateSEXP, SEXP subsampleSEXP, SEXP max_depthSEXP, SEXP min_bucketSEXP, SEXP mtrySEXP, SEXP seed_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type min_node_candidates(min_node_candidatesSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< double >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type min_bucket(min_bucketSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type seed_base(seed_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cit_oob_score_min_node_matrix(X, Y, min_node_candidates, learning_rate, subsample, max_depth, min_bucket, mtry, seed_base));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cit_residualize_matrix_one
NumericMatrix cpp_cit_residualize_matrix_one(NumericMatrix X, NumericMatrix Y, IntegerVector min_node_by_col, double learning_rate, int max_depth, int min_bucket, int mtry, int seed_base);
RcppExport SEXP _BLITZ_cpp_cit_residualize_matrix_one(SEXP XSEXP, SEXP YSEXP, SEXP min_node_by_colSEXP, SEXP learning_rateSEXP, SEXP max_depthSEXP, SEXP min_bucketSEXP, SEXP mtrySEXP, SEXP seed_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type min_node_by_col(min_node_by_colSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type min_bucket(min_bucketSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type seed_base(seed_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cit_residualize_matrix_one(X, Y, min_node_by_col, learning_rate, max_depth, min_bucket, mtry, seed_base));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BLITZ_cpp_poly_residualize_matrix", (DL_FUNC) &_BLITZ_cpp_poly_residualize_matrix, 5},
    {"_BLITZ_cpp_cit_oob_score_min_node_matrix", (DL_FUNC) &_BLITZ_cpp_cit_oob_score_min_node_matrix, 9},
    {"_BLITZ_cpp_cit_residualize_matrix_one", (DL_FUNC) &_BLITZ_cpp_cit_residualize_matrix_one, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_BLITZ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
