# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_poly_residualize_matrix <- function(Z, A, degree = 2L, interactions = TRUE, ridge = 1e-8) {
    .Call(`_BLITZ_cpp_poly_residualize_matrix`, Z, A, degree, interactions, ridge)
}

cpp_cit_oob_score_min_node_matrix <- function(X, Y, min_node_candidates, learning_rate = 1.0, subsample = 1.0, max_depth = 100L, min_bucket = 1L, mtry = 0L, seed_base = NA_integer_) {
    .Call(`_BLITZ_cpp_cit_oob_score_min_node_matrix`, X, Y, min_node_candidates, learning_rate, subsample, max_depth, min_bucket, mtry, seed_base)
}

cpp_cit_residualize_matrix_one <- function(X, Y, min_node_by_col, learning_rate = 1.0, max_depth = 100L, min_bucket = 1L, mtry = 0L, seed_base = NA_integer_) {
    .Call(`_BLITZ_cpp_cit_residualize_matrix_one`, X, Y, min_node_by_col, learning_rate, max_depth, min_bucket, mtry, seed_base)
}

